### ISSUE TITLE
WooCommerce as required plugins

### ISSUE THREAD

**Issue by Micemade** [scottyzen/woonuxt-settings#3]
Hi,

I've installed the "Woonuxt settings" on a fresh install, but before I installed WooCommerce (silly me 🙂 ), so I got the following error on settings page:

`Fatal error: Uncaught Error: Call to undefined function wc_get_attribute_taxonomies() in .../wp-content/plugins/woonuxt-settings/woonuxt.php:371 Stack trace: #0 .../wp-admin/includes/template.php(1773): global_setting_callback(Array) #1 .../wp-content/plugins/woonuxt-settings/woonuxt.php(157): do_settings_sections('woonuxt') #2 .../wp-includes/class-wp-hook.php(308): woonuxt_options_page_html('') #3 .../wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array) #4 .../wp-includes/plugin.php(517): WP_Hook->do_action(Array) #5 .../wp-admin/admin.php(259): do_action('settings_page_w...') #6 .../wp-admin/options-general.php(10): require_once('/Users/alen/Loc...') #7 {main} thrown in .../wp-content/plugins/woonuxt-settings/woonuxt.php on line 371`

So, perhaps there should be added a check for WooCommerce installation and add a WooCommerece to "Required plugins" boxes at the top of the settings page 🙂
Cheers!

**Comment by scottyzen** [comment]
Hi @Micemade. You're absolutely right. Thanks for the heads up. I'll put it on the todo list 👍🏻
