### ISSUE TITLE
Error fetching woonuxt settings

### ISSUE THREAD

**Issue by seaqcumber** [scottyzen/woonuxt-settings#9]
I'm getting this error on a fresh install, using woonuxt-settings  1.0.51

4:34:42 PM: [log] Error fetching woonuxt settings. Make sure you have the latest version woonuxt-settings plugin installed and activated WordPress. You can download it from https://github.com/scottyzen/woonuxt-settings

any ideas? Below is the log files

4:34:04 PM: build-image version: fcb0c1b3ada6d25c1cb58e8bc514f5f23cc14f15 (focal)
4:34:04 PM: buildbot version: d4068f75b500fda01f8eb2592656f157c0c28aa7
4:34:04 PM: Fetching cached dependencies
4:34:04 PM: Failed to fetch cache, continuing with build
4:34:04 PM: Starting to prepare the repo for build
4:34:04 PM: No cached dependencies found. Cloning fresh repo
4:34:04 PM: git clone --filter=blob:none https://github.com/scottyzen/woonuxt
4:34:05 PM: Preparing Git Reference refs/heads/master
4:34:07 PM: Starting to install dependencies
4:34:07 PM: Python version set to 3.8
4:34:07 PM: Attempting Ruby version 2.7.2, read from environment
4:34:08 PM: Using Ruby version 2.7.2
4:34:08 PM: Started restoring cached go cache
4:34:08 PM: Finished restoring cached go cache
4:34:10 PM: go version go1.19.13 linux/amd64
4:34:10 PM: Using PHP version 8.0
4:34:11 PM: v18.19.0 is already installed.
4:34:11 PM: Now using node v18.19.0 (npm v10.2.3)
4:34:11 PM: Enabling Node.js Corepack
4:34:11 PM: Started restoring cached build plugins
4:34:11 PM: Finished restoring cached build plugins
4:34:11 PM: Started restoring cached corepack dependencies
4:34:11 PM: Finished restoring cached corepack dependencies
4:34:11 PM: No npm workspaces detected
4:34:11 PM: Started restoring cached node modules
4:34:11 PM: Finished restoring cached node modules
4:34:12 PM: Installing npm packages using npm version 10.2.3
4:34:20 PM: npm WARN deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
4:34:20 PM: npm WARN deprecated ohmyfetch@0.4.21: Package renamed to https://github.com/unjs/ofetch
4:34:21 PM: npm WARN deprecated @babel/plugin-proposal-object-rest-spread@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.
4:34:26 PM: > postinstall
4:34:26 PM: > nuxi prepare
4:34:29 PM: [log] Error fetching woonuxt settings. Make sure you have the latest version woonuxt-settings plugin installed and activated WordPress. You can download it from https://github.com/scottyzen/woonuxt-settings
4:34:36 PM: [warn] Slow module `nuxt-graphql-client` took `5598.84ms` to setup.
4:34:36 PM: [info] [nuxt:tailwindcss] Using default Tailwind CSS file
4:34:37 PM: [success] Types generated in .nuxt
4:34:37 PM: added 1381 packages, and audited 1383 packages in 25s
4:34:37 PM: 277 packages are looking for funding
4:34:37 PM:   run `npm fund` for details
4:34:37 PM: 7 high severity vulnerabilities
4:34:37 PM: To address issues that do not require attention, run:
4:34:37 PM:   npm audit fix
4:34:37 PM: To address all issues (including breaking changes), run:
4:34:37 PM:   npm audit fix --force
4:34:37 PM: Run `npm audit` for details.
4:34:37 PM: npm packages installed
4:34:37 PM: Successfully installed dependencies
4:34:37 PM: Starting build script
4:34:38 PM: Detected 1 framework(s)
4:34:38 PM: "nuxt" at version "3.9.3"
4:34:38 PM: Section completed: initializing
4:34:39 PM: ​
4:35:39 PM: Pushing to repository git@github.com:seaqcumber/woonuxt-jv8

**Comment by scottyzen** [comment]
Hey @seaqcumber,
Can you send me your ```GQL_HOST="https://example.com/graphql"``` and I'll take a look for you.

**Comment by seaqcumber** [comment]
Hi @scottyzen , its this https://joyvicari.com/graphql

**Comment by savielmonzac** [comment]
I'm also experiencing the same issue when deploying to Netlify with the same error as @seaqcumber, [https://staging.vagcruisers.uk/graphql](https://staging.vagcruisers.uk/graphql). I did change the `GQL_HOST = "WordPress URL` in netlify.toml, not sure if this would cause further issues.

**Comment by alexookah** [comment]
Its similar to this issue:
https://github.com/scottyzen/woonuxt/issues/117#issuecomment-1905809815

It has been fixed only in repo. A new version of the woonuxt-settings haven't yet been made.

Next version should be fixed. You can download zip from master repo as a workaround for this.

**Comment by scottyzen** [comment]
> Its similar to this issue: [scottyzen/woonuxt#117 (comment)](https://github.com/scottyzen/woonuxt/issues/117#issuecomment-1905809815)
> 
> It has been fixed only in repo. A new version of the woonuxt-settings haven't yet been made.
> 
> Next version should be fixed. You can download zip from master repo as a workaround for this.

Thanks @alexookah, Will update that version later 👍

**Comment by alexookah** [comment]
version has been created.
Feel free to close the issue @seaqcumber  :)

**Comment by savmon120** [comment]
> version has been created. Feel free to close the issue @seaqcumber :)

Updated and rebuilt and all is well, thanks a lot :)

**Comment by seaqcumber** [comment]
great! thanks guys!
